### ISSUE TITLE
Feature request: Set application name via connectionstring

### ISSUE THREAD

**Issue by mrtristan** [aws/amazon-redshift-odbc-driver#10]
`void getApplicationName(SQLHDBC phdbc)` gets the calling application name and uses that - i'd like to be able to specify the application via the connectionstring as can (seemingly) be done in jdbc. if this isn't done then it should fall back to what it does today. This is a normal practice with sql server and others.

good rationale:
https://www.connectionstrings.com/use-application-name-sql-server/

**Comment by vahid110** [comment]
@mrtristan Thanks for reporting this issue and my apologies for the delay in response. I've notified our driver team so this can be investigated.

**Comment by vahid110** [comment]
@mrtristan I need a little bit more information please. I can see `ApplicationName` is a valid connection string paramenter. I also see internal usage of `void getApplicationName(SQLHDBC phdbc)`.
Do you require to be able to use a command line `SELECT APP_NAME();` ?

**Comment by mrtristan** [comment]
@vahid110 realized i still had the 1.x version and it wasn't working in that context. targeted 2.x and it's working now. thanks.
