### ISSUE TITLE
SQL Server linked server error "The provider reported an unexpected catastrophic failure."

### ISSUE THREAD

**Issue by gfody** [aws/amazon-redshift-odbc-driver#14]
## Driver version
2.0.0.11

## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.61191

## Client Operating System
Windows10 Version 22H2 (OS Build 19045.3803)

## Table schema
N/A (connectivity problem)

## Problem description
Trying to use this driver for a linked server from SQL Server, and am getting this error message:
```sql
select x from openrowset('MSDASQL', 'Driver={Amazon Redshift ODBC Driver (x64)};Host=...;Database=...;UID=...;Password=...',
    'select 1 as x')

> The OLE DB provider "MSDASQL" for linked server "(null)" reported an error. The provider reported an unexpected catastrophic failure.
> Cannot fetch a row from OLE DB provider "MSDASQL" for linked server "(null)".
```
..if I use version [1.5.9.1011](https://s3.amazonaws.com/redshift-downloads/drivers/odbc/1.5.9.1011/AmazonRedshiftODBC64-1.5.9.1011.msi) it works normally:
```sql
select x from openrowset('MSDASQL', 'Driver={Amazon Redshift (x64)};Host=...;Database=...;UID=...;Password=...',
    'select 1 as x')

> x
> 1
```

## ODBC trace logs
[amazonredshiftodbcdriver.log](https://github.com/aws/amazon-redshift-odbc-driver/files/13781841/amazonredshiftodbcdriver.log)
[amazonredshiftodbcdriver_connection_1.log](https://github.com/aws/amazon-redshift-odbc-driver/files/13781842/amazonredshiftodbcdriver_connection_1.log)

**Comment by vahid110** [comment]
Hi @gfody
Thanks for opening in an issue.
Can I ask you to kindly use the latest version ([2.1.1](https://s3.amazonaws.com/redshift-downloads/drivers/odbc/2.1.1.0/AmazonRedshiftODBC64-2.1.1.0.msi)) We have a fix for linked servers.
Thank you

**Comment by gfody** [comment]
tested with 2.1.1.0 this is working now, thank you!
