### ISSUE TITLE
Failed to get serverless credentials due to AWSCredentialsProvider being NULL.

### ISSUE THREAD

**Issue by solidstore** [aws/amazon-redshift-odbc-driver#17]
## Driver version
2.1.1

## Redshift version
N/A

## Client Operating System
Windows

## Table schema
N/A

## Problem description
Support for IAM Instance Profile. I'm trying to use the Auth Type: "AWS Profile" and "Use Instance Profile" to pick the EC2 instance role. 

1. Expected behaviour:
The EC2 instance profile should be used for credentials.

2. Actual behaviour:
Connection fails with error message.

3. Error message/stack trace:

```Connection failed[HY000]: [Redshift][ODBC Driver][Server][860:8:IAMConnectionError]: Failed to get serverless credentials due to AWSCredentialsProvider being NULL.```

4. Any other details that can be helpful:

## ODBC trace logs
[DEBUG] 2024-04-08 07:18:10.084 [IAMHLP:RsIamHelper.cpp:299] [83460] RsIamHelper::SetIamSettings
[DEBUG] 2024-04-08 07:18:10.084 [IAMHLP:RsIamHelper.cpp:350] [83460] Code flow for regular serverless cluster
[DEBUG] 2024-04-08 07:18:10.084 [IAMHLP:RsIamHelper.cpp:393] [83460] Cluster Identifier:
[DEBUG] 2024-04-08 07:18:10.084 [IAMCLNT:RsIamClient.cpp:65] [83460] RsIamClient::RsIamClient
[DEBUG] 2024-04-08 07:18:10.086 [IAMCLNT:RsIamClient.cpp:107] [83460] RsIamClient::Connect
[DEBUG] 2024-04-08 07:18:10.086 [IAMCLNT:RsIamClient.cpp:858] [83460] RsIamClient::ValidateConnectionAttributes
[DEBUG] 2024-04-08 07:18:10.086 [IAMCLNT:RsIamClient.cpp:114] [83460] RsIamClient::Connect IAM AuthType: InstanceProfile
[DEBUG] 2024-04-08 07:18:10.086 [IAMCLNT:RsIamClient.cpp:845] [83460] RsIamClient::GetServerlessCredentials
[DEBUG] 2024-04-08 07:18:10.086 [IAMCLNT:RsIamClient.cpp:214] [83460] RsIamClient::~RsIamClient
[DEBUG] 2024-04-08 07:18:10.087 [ODBCAPI:rstrace.h:96] [83460] SQLDriverConnectW() return SQL_ERROR
SQLState:HY000 NativeCode:0 Error:[Redshift][ODBC Driver][Server][860:8:IAMConnectionError]: Failed to get serverless credentials due to AWSCredentialsProvider being NULL.

## Reproduction code
Both the ```IAMFactory::CreateDefaultCredentialsProvider``` and ```IAMFactory::CreateInstanceProfileCredentialsProvider``` methods appear to return NULL pointers.
https://github.com/aws/amazon-redshift-odbc-driver/blob/main/src/odbc/rsodbc/iam/core/IAMFactory.cpp#L123

**Comment by vahid110** [comment]
Hi @solidstore, thank you for taking the time to open this issue, my apologies for the delay in response. We really appreciate you providing a reproduction of the issue as it's a big help to our team. I've notified the team of this issue and will update here as more information is available.

**Comment by cmatte** [comment]
Hi @vahid110 - the above is a major blocker to implement IAM authentication via RedShift ServerLess via ODBC and is a hard limitation in 2.1.6 ODBC driver, while the JDBC driver supports it fully, instead. Can I kindly ask what resolution was implemented between your response on 16th Apr and the closure on 11th Jul, in order to resolve/close this issue?

**Comment by meyerovb** [comment]
This now works fine actually, you have to put default into the Profile box, you didn't have to do that in v1

![Image](https://github.com/user-attachments/assets/058babd3-04a2-4f22-9c74-9268a20ea1eb)
