### ISSUE TITLE
AWSCredentialsProvider being NULL

### ISSUE THREAD

**Issue by MikeWinkelmannXL2** [aws/amazon-redshift-odbc-driver#18]
## Driver version
- 2.1.1.0 / 2.1.0.0

## Redshift version
<img width="809" alt="image" src="https://github.com/aws/amazon-redshift-odbc-driver/assets/139474168/2217e957-d149-403d-8c0c-9fc4666b48fa">

## Client Operating System
Microsoft Windows Server 2022 Datacenter on EC2

## Table schema
not relevant 

## Problem description

The driver does not work using IAM Auth (Profile) using EC2 Instance Metadata. The following error occurs: "AWSCredentialsProvider being NULL". This is probably related (or almost the same since we are not using redshift serverless) to #17.

This problem is not present on driver version 1.5.9.

<img width="296" alt="image" src="https://github.com/aws/amazon-redshift-odbc-driver/assets/139474168/ce45e7cb-f744-49f4-9750-bf81338dc02b">

1. Expected behaviour:
Successful Connection Test
2. Actual behaviour:
No connection possible
3. Error message/stack trace:
AWSCredentialsProvider being NULL

## ODBC trace logs
na

## Reproduction code
not relevant

**Comment by vahid110** [comment]
Hello @MikeWinkelmannXL2 
And thank you for reporting this issue.
A quick question to make sure I understand the issue. Are you reporting this as a regression? 
Asking because Instance Profile authentication is not yet supported in ODBC-2.x

**Comment by MikeWinkelmannXL2** [comment]
Hi @vahid110,

If Instance Profile auth is not supported yet then the behaviour would be expected. Can you provide me a link to some kind of documentation where I can understand what feature set is currently supported?

I was not aware that Instance Profile Auth is unsupported. Given the Options of the ODBC-driver I was expecting it to be supported.

**Comment by vahid110** [comment]
Hi @MikeWinkelmannXL2,

I've reviewed the [code](https://github.com/aws/amazon-redshift-odbc-driver/blob/d3b4b3ce49affe7f27ca184cd4d94d23704aa916/src/odbc/rsodbc/iam/core/IAMFactory.cpp#L123) and noticed that Instance profile authentication is not yet supported.

We'll need to update the documentation to reflect this limitation. I've also made a note to circulate this information internally and plan for future feature support.

Please let me know if you have any other questions or concerns.

**Comment by meyerovb** [comment]
Can I get a link to the updated documentation?

**Comment by meyerovb** [comment]
This now works fine actually, you have to put default into the Profile box, you didn't have to do that in v1

![Image](https://github.com/user-attachments/assets/00860286-f222-4fbc-a74b-ba2de214a531)
