### ISSUE TITLE
Latest version of driver crash when selecting from PG_TABLE_DEF

### ISSUE THREAD

**Issue by mkollind** [aws/amazon-redshift-odbc-driver#9]
## Driver version
2.0.0.6

## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.51304

## Client Operating System
Windows 10

## Table schema
PG_TABLE_DEF

## Problem description
Wen executing `select DISTINCT tablename from PG_TABLE_DEF where schemaname = 'public'"` (or any other selections on `PG_TABLE_DEF`) via the driver, the hosting application crashes (e.g., running a SQL query from PowerShell makes PowerShell crash: 
`[process exited with code 3221226356 (0xc0000374)]`. 

1. Expected behaviour: it should be possible to select data from PG_TABLE_DEF
2. Actual behaviour: the driver kills the application trying to fetch data
3. Error message/stack trace: In powershell, process exited with code 3221226356 (0xc0000374).
4. Any other details that can be helpful: Have not tried any other selections. There might be other things that causes this to happen. but no issues was seen on 2.0.0.5. 

## ODBC trace logs
DEBUGG logs are provided. 
[redshift_odbc.zip](https://github.com/aws/amazon-redshift-odbc-driver/files/11651585/redshift_odbc.zip)
(Added as zip since log.1 files cannot be uploaded.)

## Reproduction cod
A select as described above seems to trigger this. No other code tested.

**Comment by vahid110** [comment]
@mkollind Thank you for posting the issue. We'll have a look at this issue and provide a fix as soon as possible.

**Comment by mkollind** [comment]
I forgot to mention: this works in 2.0.0.5. But is broken in 2.0.0.6.

**Comment by vahid110** [comment]
@mkollind thanks again

**Comment by vahid110** [comment]
@mkollind I just installed the driver and tested. Works for me via a simple script like:

```
import pyodbc,sys,traceback
cnxn = pyodbc.connect('Driver={Amazon Redshift ODBC Driver (x64)}; Server=myserver.amazonaws.com; Port=5439 ;Database=dev;UID=awsuser;PWD=mypassword;')
cursor = cnxn.cursor()
cursor.execute("select DISTINCT tablename from PG_TABLE_DEF where schemaname = 'public'")
rows = cursor.fetchall()

for i in range(len(rows)):
    row = rows[i]
    print (row)
```

Could it be that you have unicode table names?

**Comment by mkollind** [comment]
Our database is only for testing so it contains some strange tables. I did some more digging, and it might be related to the number of rows returned, maybe? 
If I select all rows from PG_TABLE_DEF for a table that contains 1500 columns, it also crashes. 

If you just do `select * from PG_TABLE_DEF` will that not cause any issues either? 
I got another crash when doing `select * from PG_TABLE_DEF where schemaname = 'pg_catalog'`. 

When running the same tests with the 2.0.0.5 driver (or with the Simba driver) I cannot reproduce this.

**Comment by vahid110** [comment]
I am away from my test box. will get back to you on this soon. Also, will try to find the issue by code compare between the versions.

**Comment by vahid110** [comment]
@mkollind can you please try the new release and let us know if he issue still exist? Thank you

**Comment by mkollind** [comment]
This still happens with the 2.00.00.7 driver.

**Comment by vahid110** [comment]
@mkollind I see. Had a look at the logs. Seems it crashes during fetch. Since it is not reproducible at my end, can I please provide you with an engineering build with additional log messages to narrow down the search area?

**Comment by mkollind** [comment]
@vahid110 : yes, we can try out an engineering build.

**Comment by mkollind** [comment]
Looks like it works with the latest version (2.0.0.9).
